server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member-service
              uri: http://member-service
              predicates:
                - Path=/api/members/**